steps:
- name: 'gcr.io/cloud-builders/go'
  args:
    - 'get'
    - 'github.com/stephen-soltesz/tryout-cloud-builder'
  env:
    - 'PROJECT_ROOT=github.com/stephen-soltesz/tryout-cloud-builder'
artifacts:
  objects:
    location: 'gs://soltesz-$PROJECT_ID/'
    paths:
      - 'gopath/bin/tryout-cloud-builder'
